spring.application.name=oteljaeger-demo

oteljaeger.service-name=oteljaeger-demo
oteljaeger.exporter-endpoint=http://localhost:4318/v1/traces
oteljaeger.enabled=true
oteljaeger.capture-headers=true
oteljaeger.capture-bodies=true
